language: csharp
services:
  - docker
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.0
  - docker run mcr.microsoft.com/dotnet/core/sdk:3.0 /bin/sh -c "dotnet test"
script:
  - dotnet test
