language: csharp
mono: none
dotnet: 3.1.101
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ls -l
  - dotnet test
  - dotnet pack -c release src/Alyio.AspNetCore.ApiMessages/
