name: Alyio.AspNetCore.ApiMessages
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            '6.0.x'
            '7.0.x'
            '8.0.x'
            '9.0.x'
      - name: dotnet info 
        run: dotnet --info
      - name: dotnet test
        run: |
          #version=${{ matrix.dotnet-version }}
          #framework=net${version%.x} # remove .x from the end
          #dotnet test -f ${framework} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - name: dotnet pack
        run: dotnet pack -c Release src/Alyio.AspNetCore.ApiMessages/
